### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'datasets'

### ISSUE THREAD

**Issue by humbleflowers** [treangenlab/magnet#4]
I run this command with the new version of magnet
`python magnet.py -i ZYMO_D6311_14.nanoq.10.1000.fastq.gz -m ont -o ZYMO_D6311_14.magnet_1 --threads 30 -c relative_abundance.tsv`
i get this error 
```
Traceback (most recent call last):
  File "/home/vinay.kusuma/pfs-bix-prod/lemur/magnet/magnet.py", line 353, in <module>
    main()
  File "/home/vinay.kusuma/pfs-bix-prod/lemur/magnet/magnet.py", line 350, in main
    run_magnet(args)
  File "/home/vinay.kusuma/pfs-bix-prod/lemur/magnet/magnet.py", line 215, in run_magnet
    reference_metadata = prepare_reference_genomes(valid_taxids, working_directory, ncbi_taxa_db, accession_flag=accession_flag, mag_flag=mag_flag)
  File "/home/vinay.kusuma/pfs-bix-prod/lemur/magnet/utils/reference_finder.py", line 173, in prepare_reference_genomes
    download_result.append(download_reference_genome(taxid, working_dir, mag_flag=mag_flag))
  File "/home/vinay.kusuma/pfs-bix-prod/lemur/magnet/utils/reference_finder.py", line 65, in download_reference_genome
    res = run_datasets_summary(taxid, ['--reference', '--assembly-source', 'refseq'], mag_flag=mag_flag)
  File "/home/vinay.kusuma/pfs-bix-prod/lemur/magnet/utils/reference_finder.py", line 30, in run_datasets_summary
    grepOut  = subprocess.run(args,
  File "/home/ubuntu/miniforge3/envs/vk_tools/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/ubuntu/miniforge3/envs/vk_tools/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/ubuntu/miniforge3/envs/vk_tools/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'datasets'
```
Can i get any guidance on this? Thank you.

**Comment by humbleflowers** [comment]
i fixed it by downloading

`mamba install -c bioconda ncbi-datasets-cli`
